//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagemnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int maintenanceID { get; set; }
        public string maintenanceDescription { get; set; }
        public Nullable<decimal> maintenanceCost { get; set; }
        public Nullable<System.DateTime> maintenanceDate { get; set; }
        public Nullable<int> propertyID { get; set; }
        public string maintenanceTitle { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
