//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagemnet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int rentID { get; set; }
        public Nullable<int> propertyID { get; set; }
        public Nullable<int> tenantID { get; set; }
        public Nullable<decimal> RentAmount { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public int Duration { get; set; }
        public virtual Property Property { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
